FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app

COPY pom.xml .
COPY .mvn .mvn
COPY mvnw mvnw.cmd ./
# Copiem tot
COPY . .

RUN chmod +x mvnw

# Compilar tot el multimòdul i instal·lem al repo local
RUN ./mvnw clean install -DskipTests -T 1C

FROM eclipse-temurin:21-jre-alpine
WORKDIR /application
# Copiar el JAR generat
COPY --from=build /app/tfm-citaprevia-api/target/citapreviaapi.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]